baseurl = "http://ecopony.github.io/"
languageCode = "en-us"
title = "ed copony"
canonifyurls = true
description = "software developer - portland, or"

[params]
	description = "software developer - portland, or"